services:
  app:
    build: .
    container_name: grid07_app
    depends_on:
      - postgres
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/grid07db
      SPRING_DATASOURCE_USERNAME: akshat
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    ports:
      - "8080:8080"

  postgres:
    image: postgres:17
    container_name: grid07_postgres
    environment:
      POSTGRES_DB: grid07db
      POSTGRES_USER: akshat
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"

  redis:
    image: redis:8.6
    container_name: grid07_redis
    ports:
      - "6379:6379"